name: mmark-test
dependencies:
  - base

executables:
  mkdoc:
    main: app/MkDoc.hs
    dependencies:
      # - lucid
      - mmark
      # - mmark-ext
    ghc-options:
      - -threaded
      - -rtsopts
