name: mmark-test
dependencies:
  - base
  
ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Wnoncanonical-monad-instances
- -Wredundant-constraints
- -Wtabs

library:
  source-dirs: src
  
executables:
  mkdoc:
    main: app/MkDoc.hs
    dependencies:
      - lucid
      - mmark
      - mmark-ext
    ghc-options:
      - -threaded
      - -rtsopts
